name: pp1-swallow
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.3.1
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - aom=3.9.1
  - appdirs=1.4.4
  - attr=2.5.2
  - audioread=3.0.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - click=8.2.1
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpython=3.10.18
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-tools=12.9.86
  - cuda-opencl=12.9.19
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - cudnn=9.12.0.46
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - decorator=5.2.1
  - docker-pycreds=0.4.0
  - double-conversion=3.3.1
  - eval_type_backport=0.2.2
  - ffmpeg=8.0.0
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.2
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.7.0
  - future=1.0.0
  - gdk-pixbuf=2.42.12
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glslang=15.4.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - grpcio=1.74.1
  - h2=4.3.0
  - harfbuzz=11.4.5
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.24.2
  - libabseil=20250512.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcublas=12.4.5.8
  - libcudnn=9.12.0.46
  - libcudnn-dev=9.12.0.46
  - libcudss=0.6.0.5
  - libcufft=11.2.1.3
  - libcufile=1.14.1.1
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libgrpc=1.74.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libmagma=2.8.0
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvfatbin=12.9.82
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.31.1
  - libre2-11=2025.07.22
  - librosa=0.11.0
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtiff=4.7.0
  - libudev1=257.7
  - libunwind=1.8.2
  - liburing=2.12
  - libusb=1.0.29
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - markdown=3.8.2
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - munkres=1.1.4
  - nccl=2.27.7.1
  - ncurses=6.5
  - networkx=3.4.2
  - numba=0.61.2
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - omegaconf=2.3.0
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.2
  - optree=0.17.0
  - packaging=25.0
  - pandas=2.3.2
  - pango=1.56.4
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - pooch=1.8.2
  - protobuf=6.31.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pyloudnorm=0.1.1
  - pyparsing=3.2.3
  - pyside6=6.9.2
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.9.2
  - rdma-core=59.0
  - re2=2025.07.22
  - readline=8.2
  - requests=2.32.5
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl3=3.2.22
  - sentry-sdk=2.35.2
  - setproctitle=1.3.6
  - setuptools=80.9.0
  - shaderc=2025.3
  - six=1.17.0
  - sleef=3.9.0
  - smmap=5.0.2
  - snappy=1.2.2
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - spirv-tools=2025.1
  - standard-aifc=3.13.0
  - standard-sunau=3.13.0
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2021.13.0
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - typing=3.10.0.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - uv=0.8.14
  - wandb=0.21.1
  - wayland=1.24.0
  - wayland-protocols=1.45
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
